<?xml version="1.0" standalone="yes" ?>
<!DOCTYPE stocks [
        <!ELEMENT stocks (stock)*>
        <!ELEMENT stock (name|sector)*>
        <!ATTLIST stock
                dividends CDATA #REQUIRED
                frequency CDATA #REQUIRED
                id CDATA #REQUIRED
                mcp CDATA #REQUIRED
                numberOfShares CDATA #REQUIRED
                price CDATA #REQUIRED
                sector CDATA #REQUIRED
                ticker CDATA #REQUIRED>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT sector (#PCDATA)>

        <!ENTITY e1 "Manufacturing">
        <!ENTITY e2 "Missing">
        <!ENTITY e3 "Accommodation and Food Services">
        <!ENTITY e4 "Utilities">
        <!ENTITY e5 "Information">
        <!ENTITY e6 "Construction">
        <!ENTITY e7 "Public Administration">
        <!ENTITY e8 "Finance and Insurance">
        <!ENTITY e9 "Real Estate and Rental and Leasing">
        <!ENTITY e10 "Other">
        <!ENTITY e11 "Management of Companies and Enterprises">
        <!ENTITY e12 "Arts, Entertainment, and Recreation">
        <!ENTITY e13 "Retail Trade">
        <!ENTITY e14 "Health Care and Social Assistance">
        <!ENTITY e15 "Mining, Quarrying, and Oil and Gas Extraction">
        <!ENTITY e16 "Transportation and Warehousing">
        <!ENTITY e17 "Administrative and Support and Waste Management and Remediation Services">
        <!ENTITY e18 "Professional, Scientific, and Technical Services">
        <!ENTITY e19 "Wholesale Trade">
        ]>
<stocks>
    <stock id="1" ticker="BKR" sector="&e1;" price="25.18" numberOfShares="77" mcp="26.0673432" dividends="0.028254705"
           frequency="quarterly">
        <name>Baker Hughes Co</name>
    </stock>
    <stock id="2" ticker="HES" sector="&e1;" price="81.14" numberOfShares="24" mcp="25.12686333" dividends="0.012264182"
           frequency="quarterly">
        <name>Hess Corporation</name>
    </stock>
    <stock id="3" ticker="HLT" sector="&e3;" price="138.15" numberOfShares="14" mcp="38.50047131" dividends="0"
           frequency="N/A">
        <name>Hilton Worldwide Holdings Inc</name>
    </stock>
    <stock id="4" ticker="AES" sector="&e4;" price="22.9" numberOfShares="85" mcp="15.25963802" dividends="0.025744337"
           frequency="quarterly">
        <name>AES Corp.</name>
    </stock>
    <stock id="5" ticker="T" sector="&e5;" price="27.16" numberOfShares="72" mcp="193.9224" dividends="0.075612195"
           frequency="quarterly">
        <name>AT AND T, Inc.</name>
    </stock>
    <stock id="6" ticker="VNO" sector="&e8;" price="43.49" numberOfShares="44" mcp="8.330977278" dividends="0.047862244"
           frequency="quarterly">
        <name>Vornado Realty Trust</name>
    </stock>
    <stock id="7" ticker="GE" sector="&e1;" price="105.82" numberOfShares="18" mcp="116.402" dividends="0.003020536"
           frequency="quarterly">
        <name>General Electric Co.</name>
    </stock>
    <stock id="8" ticker="BMY" sector="&e1;" price="59.51" numberOfShares="32" mcp="132.2379775" dividends="0.032553442"
           frequency="quarterly">
        <name>Bristol-Myers Squibb Co.</name>
    </stock>
    <stock id="9" ticker="VLO" sector="&e1;" price="73.62" numberOfShares="26" mcp="30.09758092" dividends="0.052155026"
           frequency="quarterly">
        <name>Valero Energy Corp.</name>
    </stock>
    <stock id="10" ticker="LVS" sector="&e12;" price="38.18" numberOfShares="51" mcp="29.16912873" dividends="0"
           frequency="N/A">
        <name>Las Vegas Sands Corp</name>
    </stock>
    <stock id="11" ticker="WRK" sector="&e1;" price="50.93" numberOfShares="38" mcp="13.59862083"
           dividends="0.017172622" frequency="quarterly">
        <name>WestRock Co</name>
    </stock>
    <stock id="12" ticker="MRO" sector="&e15;" price="14.24" numberOfShares="137" mcp="11.22679952"
           dividends="0.008399051" frequency="quarterly">
        <name>Marathon Oil Corporation</name>
    </stock>
    <stock id="13" ticker="HST" sector="&e8;" price="16.77" numberOfShares="116" mcp="11.97333531" dividends="0"
           frequency="N/A">
        <name>Host Hotels AND Resorts Inc</name>
    </stock>
    <stock id="14" ticker="LUV" sector="&e16;" price="54.35" numberOfShares="36" mcp="32.15588167" dividends="0"
           frequency="N/A">
        <name>Southwest Airlines Co</name>
    </stock>
    <stock id="15" ticker="XOM" sector="&e1;" price="60.93" numberOfShares="32" mcp="257.9509885"
           dividends="0.055840599" frequency="quarterly">
        <name>Exxon Mobil Corp.</name>
    </stock>
    <stock id="16" ticker="PSX" sector="&e1;" price="72.57" numberOfShares="26" mcp="31.78489134" dividends="0.04874598"
           frequency="quarterly">
        <name>Phillips 66</name>
    </stock>
    <stock id="17" ticker="PRGO" sector="&e1;" price="48.56" numberOfShares="40" mcp="6.493189765"
           dividends="0.019300248" frequency="quarterly">
        <name>Perrigo Company plc</name>
    </stock>
    <stock id="18" ticker="TAP" sector="&e1;" price="47.13" numberOfShares="41" mcp="9.593811655"
           dividends="0.007214089" frequency="quarterly">
        <name>Molson Coors Beverage Company</name>
    </stock>
    <stock id="19" ticker="PPL" sector="&e4;" price="27.96" numberOfShares="69" mcp="21.51817887"
           dividends="0.058131844" frequency="quarterly">
        <name>PPL Corp</name>
    </stock>
    <stock id="20" ticker="MGM" sector="&e12;" price="44.86" numberOfShares="43" mcp="21.61715371"
           dividends="0.000222896" frequency="quarterly">
        <name>MGM Resorts International</name>
    </stock>
    <stock id="21" ticker="HBI" sector="&e1;" price="17.47" numberOfShares="112" mcp="6.099680321"
           dividends="0.033946993" frequency="quarterly">
        <name>Hanesbrands Inc</name>
    </stock>
    <stock id="22" ticker="EXPE" sector="&e17;" price="169.79" numberOfShares="11" mcp="24.66986727" dividends="0"
           frequency="N/A">
        <name>Expedia Group Inc</name>
    </stock>
    <stock id="23" ticker="BA" sector="&e1;" price="226" numberOfShares="8" mcp="132.4703303" dividends="0"
           frequency="N/A">
        <name>Boeing Co.</name>
    </stock>
    <stock id="24" ticker="LUMN" sector="&e5;" price="12.68" numberOfShares="154" mcp="14.01434345"
           dividends="0.076615516" frequency="quarterly">
        <name>Lumen Technologies Inc</name>
    </stock>
    <stock id="25" ticker="LYV" sector="&e18;" price="98.73" numberOfShares="19" mcp="21.6208909" dividends="0"
           frequency="N/A">
        <name>Live Nation Entertainment Inc</name>
    </stock>
    <stock id="26" ticker="FANG" sector="&e15;" price="98.86" numberOfShares="19" mcp="17.89896364"
           dividends="0.016308713" frequency="quarterly">
        <name>Diamondback Energy Inc</name>
    </stock>
    <stock id="27" ticker="ALK" sector="&e16;" price="62.2" numberOfShares="31" mcp="7.789475246" dividends="0"
           frequency="N/A">
        <name>Alaska Air Group Inc.</name>
    </stock>
    <stock id="28" ticker="NOV" sector="&e1;" price="13.48" numberOfShares="145" mcp="5.266691672" dividends="0"
           frequency="N/A">
        <name>NOV Inc</name>
    </stock>
    <stock id="29" ticker="VTRS" sector="&e8;" price="13.6" numberOfShares="143" mcp="16.44635026"
           dividends="0.016115928" frequency="quarterly">
        <name>Viatris Inc</name>
    </stock>
    <stock id="30" ticker="WYNN" sector="&e12;" price="87.21" numberOfShares="22" mcp="10.08772311" dividends="0"
           frequency="N/A">
        <name>Wynn Resorts Ltd.</name>
    </stock>
    <stock id="31" ticker="MCK" sector="&e19;" price="200.02" numberOfShares="9" mcp="30.93800769"
           dividends="0.008620183" frequency="quarterly">
        <name>Mckesson Corporation</name>
    </stock>
    <stock id="32" ticker="ABC" sector="&e19;" price="119.81" numberOfShares="16" mcp="24.89497437"
           dividends="0.014607494" frequency="quarterly">
        <name>Amerisource Bergen Corp.</name>
    </stock>
    <stock id="33" ticker="OXY" sector="&e15;" price="31.15" numberOfShares="62" mcp="29.08583394"
           dividends="0.001283395" frequency="quarterly">
        <name>Occidental Petroleum Corp.</name>
    </stock>
    <stock id="34" ticker="RCL" sector="&e16;" price="92.33" numberOfShares="21" mcp="23.51591623" dividends="0"
           frequency="N/A">
        <name>Royal Caribbean Group</name>
    </stock>
    <stock id="35" ticker="DAL" sector="&e16;" price="45.38" numberOfShares="43" mcp="29.03933716" dividends="0"
           frequency="N/A">
        <name>Delta Air Lines, Inc.</name>
    </stock>
    <stock id="36" ticker="CCL" sector="&e17;" price="26.09" numberOfShares="75" mcp="28.80309952" dividends="0"
           frequency="N/A">
        <name>Carnival Corp.</name>
    </stock>
    <stock id="37" ticker="UAL" sector="&e16;" price="51.34" numberOfShares="38" mcp="16.61428428" dividends="0"
           frequency="N/A">
        <name>United Airlines Holdings Inc</name>
    </stock>
    <stock id="38" ticker="AAL" sector="&e16;" price="21.65" numberOfShares="90" mcp="14.01746204" dividends="0"
           frequency="N/A">
        <name>American Airlines Group Inc</name>
    </stock>
    <stock id="39" ticker="NCLH" sector="&e16;" price="28.31" numberOfShares="69" mcp="6.083819" dividends="0"
           frequency="N/A">
        <name>Norwegian Cruise Line Holdings Ltd</name>
    </stock>
    <stock id="40" ticker="CXO" sector="&e15;" price="65.6" numberOfShares="29" mcp="12.87758438" dividends="0.01212016"
           frequency="quarterly">
        <name>Concho Resources Inc</name>
    </stock>
    <stock id="41" ticker="MXIM" sector="&e1;" price="103.14" numberOfShares="18" mcp="0" dividends="0" frequency="N/A">
        <name>Maxim Integrated Products, Inc.</name>
    </stock>
    <stock id="42" ticker="UA" sector="&e1;" price="18.06" numberOfShares="108" mcp="8.76328992" dividends="0"
           frequency="N/A">
        <name>Under Armour Inc</name>
    </stock>
    <stock id="43" ticker="DISCK" sector="&e5;" price="24.78" numberOfShares="78" mcp="12.8739203" dividends="0"
           frequency="N/A">
        <name>Discovery Inc</name>
    </stock>
    <stock id="44" ticker="NWS" sector="&e5;" price="23.58" numberOfShares="82" mcp="13.98219483"
           dividends="0.008461972" frequency="semi-annual">
        <name>News Corp</name>
    </stock>
    <stock id="45" ticker="AON" sector="&e8;" price="291.08" numberOfShares="6" mcp="65.71047955"
           dividends="0.006645106" frequency="quarterly">
        <name>Aon plc.</name>
    </stock>
    <stock id="46" ticker="QQQ" sector="&e2;" price="360.18" numberOfShares="5" mcp="183.025467" dividends="0.004895886"
           frequency="quarterly">
        <name>Invesco Capital Management LLC</name>
    </stock>
    <stock id="47" ticker="ONON" sector="&e1;" price="30.5" numberOfShares="64" mcp="0" dividends="0" frequency="N/A">
        <name>On Holding AG</name>
    </stock>
    <stock id="48" ticker="FLIR" sector="&e1;" price="57.34" numberOfShares="34" mcp="0" dividends="0"
           frequency="quarterly">
        <name>Flir Systems, Inc.</name>
    </stock>
    <stock id="49" ticker="TROW" sector="&e8;" price="198.54" numberOfShares="9" mcp="45.05604935"
           dividends="0.020459462" frequency="quarterly">
        <name>T. Rowe Price Group Inc.</name>
    </stock>
    <stock id="50" ticker="ALXN" sector="&e1;" price="182.5" numberOfShares="10" mcp="0" dividends="0" frequency="N/A">
        <name>Alexion Pharmaceuticals Inc.</name>
    </stock>
    <stock id="51" ticker="FOX" sector="&e5;" price="37.68" numberOfShares="51" mcp="22.66046423"
           dividends="0.012430777" frequency="semi-annual">
        <name>Fox Corporation</name>
    </stock>
    <stock id="52" ticker="GOOG" sector="&e5;" price="2729.25" numberOfShares="0" mcp="1842.710474" dividends="0"
           frequency="N/A">
        <name>Alphabet Inc</name>
    </stock>
    <stock id="53" ticker="BRK.B" sector="&e11;" price="275.71" numberOfShares="7" mcp="624.0809227" dividends="0"
           frequency="N/A">
        <name>Berkshire Hathaway Inc.</name>
    </stock>
    <stock id="54" ticker="EBAY" sector="&e5;" price="69.91" numberOfShares="27" mcp="45.44540133"
           dividends="0.009973743" frequency="quarterly">
        <name>EBay Inc.</name>
    </stock>
    <stock id="55" ticker="MPC" sector="&e1;" price="63.56" numberOfShares="30" mcp="40.56413043"
           dividends="0.036058612" frequency="quarterly">
        <name>Marathon Petroleum Corp</name>
    </stock>
    <stock id="56" ticker="BIO" sector="&e1;" price="741.92" numberOfShares="2" mcp="22.06949116" dividends="0"
           frequency="N/A">
        <name>Bio-Rad Laboratories Inc.</name>
    </stock>
    <stock id="57" ticker="PRU" sector="&e8;" price="106.18" numberOfShares="18" mcp="40.98548" dividends="0.042130075"
           frequency="quarterly">
        <name>Prudential Financial Inc.</name>
    </stock>
    <stock id="58" ticker="DD" sector="&e1;" price="69.13" numberOfShares="28" mcp="36.15890912" dividends="0.01725644"
           frequency="quarterly">
        <name>DuPont de Nemours Inc</name>
    </stock>
    <stock id="59" ticker="GM" sector="&e1;" price="53.13" numberOfShares="36" mcp="77.13008613" dividends="0"
           frequency="N/A">
        <name>General Motors Company</name>
    </stock>
    <stock id="60" ticker="AFL" sector="&e8;" price="52.94" numberOfShares="36" mcp="35.50904702"
           dividends="0.023820532" frequency="quarterly">
        <name>Aflac Inc.</name>
    </stock>
    <stock id="61" ticker="ZION" sector="&e8;" price="63.65" numberOfShares="30" mcp="10.31578497"
           dividends="0.021788629" frequency="quarterly">
        <name>Zions Bancorporation N.A</name>
    </stock>
    <stock id="62" ticker="COF" sector="&e8;" price="166.54" numberOfShares="11" mcp="74.29578709"
           dividends="0.00897932" frequency="unspecified">
        <name>Capital One Financial Corp.</name>
    </stock>
    <stock id="63" ticker="CINF" sector="&e8;" price="114.79" numberOfShares="17" mcp="18.50218268"
           dividends="0.02151978" frequency="quarterly">
        <name>Cincinnati Financial Corp.</name>
    </stock>
    <stock id="64" ticker="GS" sector="&e8;" price="380" numberOfShares="5" mcp="128.0970454" dividends="0.015049058"
           frequency="quarterly">
        <name>Goldman Sachs Group, Inc.</name>
    </stock>
    <stock id="65" ticker="WHR" sector="&e1;" price="205.21" numberOfShares="9" mcp="12.86738421"
           dividends="0.025598545" frequency="quarterly">
        <name>Whirlpool Corp.</name>
    </stock>
    <stock id="66" ticker="CE" sector="&e1;" price="153.32" numberOfShares="12" mcp="17.03621957"
           dividends="0.017231693" frequency="quarterly">
        <name>Celanese Corp</name>
    </stock>
    <stock id="67" ticker="C" sector="&e8;" price="71.18" numberOfShares="27" mcp="144.2665693" dividends="0.028342491"
           frequency="quarterly">
        <name>Citigroup Inc</name>
    </stock>
    <stock id="68" ticker="PHM" sector="&e6;" price="46.13" numberOfShares="42" mcp="11.97185642"
           dividends="0.012089339" frequency="quarterly">
        <name>PulteGroup Inc</name>
    </stock>
    <stock id="69" ticker="UNM" sector="&e8;" price="25.85" numberOfShares="75" mcp="5.283575594"
           dividends="0.043983267" frequency="quarterly">
        <name>Unum Group</name>
    </stock>
    <stock id="70" ticker="RE" sector="&e8;" price="252.03" numberOfShares="7" mcp="10.00170797" dividends="0.024386691"
           frequency="quarterly">
        <name>Everest Re Group Ltd</name>
    </stock>
    <stock id="71" ticker="COO" sector="&e1;" price="416.88" numberOfShares="4" mcp="22.23662933"
           dividends="0.000143921" frequency="semi-annual">
        <name>Cooper Companies, Inc.</name>
    </stock>
    <stock id="72" ticker="VIAC" sector="&e5;" price="39.9" numberOfShares="49" mcp="25.90162073"
           dividends="0.023868573" frequency="quarterly">
        <name>ViacomCBS Inc</name>
    </stock>
    <stock id="73" ticker="DGX" sector="&e1;" price="143.3" numberOfShares="13" mcp="17.50850277"
           dividends="0.016431707" frequency="quarterly">
        <name>Quest Diagnostics, Inc.</name>
    </stock>
    <stock id="74" ticker="LYB" sector="&e1;" price="95.83" numberOfShares="20" mcp="32.05660772"
           dividends="0.044806958" frequency="quarterly">
        <name>LyondellBasell Industries NV</name>
    </stock>
    <stock id="75" ticker="HPQ" sector="&e1;" price="28.07" numberOfShares="69" mcp="32.35120098"
           dividends="0.027484998" frequency="quarterly">
        <name>HP Inc</name>
    </stock>
    <stock id="76" ticker="DFS" sector="&e8;" price="127.19" numberOfShares="15" mcp="38.08939088"
           dividends="0.010810406" frequency="quarterly">
        <name>Discover Financial Services</name>
    </stock>
    <stock id="77" ticker="DHI" sector="&e6;" price="83.75" numberOfShares="23" mcp="29.99790766"
           dividends="0.009527718" frequency="quarterly">
        <name>D.R. Horton Inc.</name>
    </stock>
    <stock id="78" ticker="CI" sector="&e8;" price="202.6" numberOfShares="9" mcp="68.9057874" dividends="0.014787989"
           frequency="quarterly">
        <name>Cigna Corp.</name>
    </stock>
    <stock id="79" ticker="RF" sector="&e8;" price="21.74" numberOfShares="90" mcp="20.75168453" dividends="0.028882113"
           frequency="quarterly">
        <name>Regions Financial Corp.</name>
    </stock>
    <stock id="80" ticker="LEN" sector="&e6;" price="93.7" numberOfShares="20" mcp="28.75138478" dividends="0.010631618"
           frequency="quarterly">
        <name>Lennar Corp.</name>
    </stock>
    <stock id="81" ticker="SYF" sector="&e8;" price="49.91" numberOfShares="39" mcp="28.43368288"
           dividends="0.017501492" frequency="quarterly">
        <name>Synchrony Financial</name>
    </stock>
    <stock id="82" ticker="HOLX" sector="&e1;" price="72.22" numberOfShares="27" mcp="18.30685923" dividends="0"
           frequency="N/A">
        <name>Hologic, Inc.</name>
    </stock>
    <stock id="83" ticker="L" sector="&e8;" price="55.27" numberOfShares="35" mcp="14.21948059" dividends="0.00451559"
           frequency="quarterly">
        <name>Loews Corp.</name>
    </stock>
    <stock id="84" ticker="NRG" sector="&e4;" price="40.66" numberOfShares="48" mcp="9.952627981"
           dividends="0.030981972" frequency="quarterly">
        <name>NRG Energy Inc.</name>
    </stock>
    <stock id="85" ticker="NRZ" sector="&e8;" price="10.93" numberOfShares="179" mcp="5.099718526"
           dividends="0.075532647" frequency="quarterly">
        <name>New Residential Investment Corp</name>
    </stock>
    <stock id="86" ticker="DISH" sector="&e5;" price="45.16" numberOfShares="43" mcp="23.75384352" dividends="0"
           frequency="N/A">
        <name>Dish Network Corp</name>
    </stock>
    <stock id="87" ticker="LH" sector="&e1;" price="279.48" numberOfShares="7" mcp="26.941872" dividends="0"
           frequency="N/A">
        <name>Laboratory Corp. Of America Holdings</name>
    </stock>
    <stock id="88" ticker="LNC" sector="&e8;" price="70.21" numberOfShares="27" mcp="13.19409609"
           dividends="0.023396315" frequency="quarterly">
        <name>Lincoln National Corp.</name>
    </stock>
    <stock id="89" ticker="CB" sector="&e8;" price="175.41" numberOfShares="11" mcp="76.95938919"
           dividends="0.017893936" frequency="quarterly">
        <name>Chubb Limited</name>
    </stock>
    <stock id="90" ticker="KEY" sector="&e8;" price="22.34" numberOfShares="87" mcp="21.36530808"
           dividends="0.032699126" frequency="quarterly">
        <name>Keycorp</name>
    </stock>
    <stock id="91" ticker="NUE" sector="&e1;" price="97.65" numberOfShares="20" mcp="28.67927125"
           dividends="0.016484562" frequency="quarterly">
        <name>Nucor Corp.</name>
    </stock>
    <stock id="92" ticker="ALL" sector="&e8;" price="127.72" numberOfShares="15" mcp="37.76442943"
           dividends="0.02306213" frequency="quarterly">
        <name>Allstate Corp (The)</name>
    </stock>
    <stock id="93" ticker="REGN" sector="&e1;" price="570.79" numberOfShares="3" mcp="59.99368719" dividends="0"
           frequency="N/A">
        <name>Regeneron Pharmaceuticals, Inc.</name>
    </stock>
    <stock id="94" ticker="PGR" sector="&e8;" price="90.94" numberOfShares="21" mcp="53.21484381"
           dividends="0.053778182" frequency="quarterly">
        <name>Progressive Corp.</name>
    </stock>
    <stock id="95" ticker="TRV" sector="&e8;" price="152.42" numberOfShares="12" mcp="38.02770782"
           dividends="0.022514544" frequency="quarterly">
        <name>Travelers Companies Inc.</name>
    </stock>
    <stock id="96" ticker="NLSN" sector="&e18;" price="19.45" numberOfShares="100" mcp="6.978662898"
           dividends="0.012294201" frequency="quarterly">
        <name>Nielsen Holdings plc</name>
    </stock>
    <stock id="97" ticker="MOS" sector="&e1;" price="37.8" numberOfShares="51" mcp="14.36010448" dividends="0.006595589"
           frequency="quarterly">
        <name>Mosaic Company</name>
    </stock>
    <stock id="98" ticker="TD" sector="&e8;" price="67.6" numberOfShares="28" mcp="123.2111043" dividends="0.04640198"
           frequency="quarterly">
        <name>Toronto Dominion Bank</name>
    </stock>
    <stock id="99" ticker="BBY" sector="&e13;" price="105.31" numberOfShares="18" mcp="25.90249201"
           dividends="0.024942668" frequency="quarterly">
        <name>Best Buy Co. Inc.</name>
    </stock>
    <stock id="100" ticker="CMA" sector="&e8;" price="82.57" numberOfShares="23" mcp="11.05807578"
           dividends="0.032486927" frequency="quarterly">
        <name>Comerica, Inc.</name>
    </stock>
    <stock id="101" ticker="WU" sector="&e5;" price="20.54" numberOfShares="95" mcp="8.346392069" dividends="0.04458965"
           frequency="quarterly">
        <name>Western Union Company</name>
    </stock>
    <stock id="102" ticker="HII" sector="&e1;" price="194.18" numberOfShares="10" mcp="7.794517631"
           dividends="0.023288247" frequency="quarterly">
        <name>Huntington Ingalls Industries Inc</name>
    </stock>
    <stock id="103" ticker="FOXA" sector="&e5;" price="40.78" numberOfShares="47" mcp="22.66046423"
           dividends="0.011488748" frequency="semi-annual">
        <name>Fox Corporation</name>
    </stock>
    <stock id="104" ticker="DOW" sector="&e15;" price="58.58" numberOfShares="33" mcp="43.68731134"
           dividends="0.047047567" frequency="quarterly">
        <name>Dow Inc</name>
    </stock>
    <stock id="105" ticker="CFG" sector="&e8;" price="48.27" numberOfShares="40" mcp="20.56703351"
           dividends="0.031881221" frequency="quarterly">
        <name>Citizens Financial Group Inc</name>
    </stock>
    <stock id="106" ticker="JPM" sector="&e8;" price="167.13" numberOfShares="11" mcp="499.4104045"
           dividends="0.021346798" frequency="quarterly">
        <name>JPMorgan Chase AND Co.</name>
    </stock>
    <stock id="107" ticker="CM" sector="&e8;" price="112.43" numberOfShares="17" mcp="50.62992091"
           dividends="0.051149438" frequency="quarterly">
        <name>Canadian Imperial Bank Of Commerce</name>
    </stock>
    <stock id="108" ticker="UHS" sector="&e14;" price="138.83" numberOfShares="14" mcp="11.79766234"
           dividends="0.002879375" frequency="quarterly">
        <name>Universal Health Services, Inc.</name>
    </stock>
    <stock id="109" ticker="IVZ" sector="&e8;" price="24.59" numberOfShares="79" mcp="11.34562397"
           dividends="0.026186532" frequency="quarterly">
        <name>Invesco Ltd</name>
    </stock>
    <stock id="110" ticker="RJF" sector="&e8;" price="94.68" numberOfShares="20" mcp="12.98935002"
           dividends="0.010936418" frequency="quarterly">
        <name>Raymond James Financial, Inc.</name>
    </stock>
    <stock id="111" ticker="PFG" sector="&e8;" price="65.63" numberOfShares="29" mcp="17.61470557"
           dividends="0.035475841" frequency="quarterly">
        <name>Principal Financial Group Inc</name>
    </stock>
    <stock id="112" ticker="VZ" sector="&e5;" price="54.3" numberOfShares="36" mcp="224.8082992" dividends="0.045497479"
           frequency="quarterly">
        <name>Verizon Communications Inc</name>
    </stock>
    <stock id="113" ticker="AIG" sector="&e8;" price="55.48" numberOfShares="35" mcp="47.44663121"
           dividends="0.022861467" frequency="quarterly">
        <name>American International Group Inc</name>
    </stock>
    <stock id="114" ticker="HIG" sector="&e8;" price="71.01" numberOfShares="27" mcp="24.65365358"
           dividends="0.019207205" frequency="quarterly">
        <name>Hartford Financial Services Group Inc.</name>
    </stock>
    <stock id="115" ticker="FDX" sector="&e16;" price="222.53" numberOfShares="8" mcp="59.11510696"
           dividends="0.012534659" frequency="quarterly">
        <name>Fedex Corp</name>
    </stock>
    <stock id="116" ticker="APA" sector="&e2;" price="21.8" numberOfShares="89" mcp="8.24086955" dividends="0.002291945"
           frequency="quarterly">
        <name>APA Corporation</name>
    </stock>
    <stock id="117" ticker="WY" sector="&e8;" price="35.77" numberOfShares="54" mcp="26.81977368"
           dividends="0.018877138" frequency="interim">
        <name>Weyerhaeuser Co.</name>
    </stock>
    <stock id="118" ticker="MTB" sector="&e8;" price="152.8" numberOfShares="12" mcp="19.66197181"
           dividends="0.028477046" frequency="quarterly">
        <name>M AND T Bank Corp</name>
    </stock>
    <stock id="119" ticker="GPS" sector="&e13;" price="23.57" numberOfShares="83" mcp="8.864796382"
           dividends="0.01537972" frequency="quarterly">
        <name>Gap, Inc.</name>
    </stock>
    <stock id="120" ticker="INTC" sector="&e1;" price="53.86" numberOfShares="36" mcp="218.51002" dividends="0.02524719"
           frequency="quarterly">
        <name>Intel Corp.</name>
    </stock>
    <stock id="121" ticker="OMC" sector="&e18;" price="74.13" numberOfShares="26" mcp="15.89404347"
           dividends="0.036602985" frequency="quarterly">
        <name>Omnicom Group, Inc.</name>
    </stock>
    <stock id="122" ticker="GL" sector="&e8;" price="90.27" numberOfShares="21" mcp="9.182319284"
           dividends="0.008613379" frequency="quarterly">
        <name>Globe Life Inc</name>
    </stock>
    <stock id="123" ticker="MHK" sector="&e1;" price="179.23" numberOfShares="10" mcp="12.37211086" dividends="0"
           frequency="N/A">
        <name>Mohawk Industries, Inc.</name>
    </stock>
    <stock id="124" ticker="MET" sector="&e8;" price="62.52" numberOfShares="31" mcp="53.57322926"
           dividends="0.029721467" frequency="quarterly">
        <name>Metlife Inc</name>
    </stock>
    <stock id="125" ticker="FITB" sector="&e8;" price="43.66" numberOfShares="44" mcp="30.1567598"
           dividends="0.025165962" frequency="quarterly">
        <name>Fifth Third Bancorp</name>
    </stock>
    <stock id="126" ticker="DISCA" sector="&e5;" price="25.74" numberOfShares="76" mcp="12.8739203" dividends="0"
           frequency="N/A">
        <name>Discovery Inc</name>
    </stock>
    <stock id="127" ticker="TSN" sector="&e1;" price="78.31" numberOfShares="24" mcp="28.51549016"
           dividends="0.02253329" frequency="quarterly">
        <name>Tyson Foods, Inc.</name>
    </stock>
    <stock id="128" ticker="CAG" sector="&e1;" price="33.7" numberOfShares="58" mcp="16.18724097"
           dividends="0.033343381" frequency="quarterly">
        <name>Conagra Brands Inc</name>
    </stock>
    <stock id="129" ticker="CPB" sector="&e1;" price="41.53" numberOfShares="47" mcp="12.52203187"
           dividends="0.034751023" frequency="quarterly">
        <name>Campbell Soup Co.</name>
    </stock>
    <stock id="130" ticker="TPR" sector="&e1;" price="38.02" numberOfShares="51" mcp="10.58174233"
           dividends="0.006575487" frequency="quarterly">
        <name>Tapestry Inc</name>
    </stock>
    <stock id="131" ticker="NOC" sector="&e1;" price="360.92" numberOfShares="5" mcp="57.78657746"
           dividends="0.016628955" frequency="quarterly">
        <name>Northrop Grumman Corp.</name>
    </stock>
    <stock id="132" ticker="BEN" sector="&e8;" price="30.1" numberOfShares="65" mcp="15.13591094"
           dividends="0.036713199" frequency="quarterly">
        <name>Franklin Resources, Inc.</name>
    </stock>
    <stock id="133" ticker="USB" sector="&e8;" price="60.76" numberOfShares="32" mcp="90.0841561"
           dividends="0.027998623" frequency="quarterly">
        <name>U.S. Bancorp.</name>
    </stock>
    <stock id="134" ticker="STT" sector="&e8;" price="86.41" numberOfShares="22" mcp="29.68210408"
           dividends="0.024419589" frequency="quarterly">
        <name>State Street Corp.</name>
    </stock>
    <stock id="135" ticker="BK" sector="&e8;" price="52.92" numberOfShares="36" mcp="45.67915104"
           dividends="0.023759898" frequency="quarterly">
        <name>Bank Of New York Mellon Corp</name>
    </stock>